bazelbuild/rules_cc

cc/BUILD

This target will eventually be the canonical place for C++ toolchain
type. Currently the actual target resides in @bazel_tools, but that will
soon change.

Add //cc:toolchain_type alias to allow forward migration with Bazel 0.27

---

cc/find_cc_toolchain.bzl

This is to help migrating for:
* https://github.com/bazelbuild/bazel/issues/7260
* https://github.com/bazelbuild/bazel/issues/7643
It's mostly a copy of the file in
`@bazel_tools//tools/cpp:toolchain_utils.bzl`, with a small difference -
it depends on `@rules_cc//cc:toolchain_type`, not on
`@bazel_tools//tools/cpp:toolchain_type`.

Add find_cc_toolchain.bzl to help accessing current C++ toolchain

---

cc/repositories.bzl

See bazelbuild/bazel-skylib#164.

Placed GitHub release first for @skylib.

---

cc/repositories.bzl

I have no clue what happened, but it seems skylib release on github was
changed after rules_cc started to depend on it.

Fix sha hash of the skylib release, and put mirror first

---

WORKSPACE
cc/repositories.bzl
internal_deps.bzl
internal_setup.bzl

As a result of this commit, rules_cc now contains the required bzl files to be tested as part of the Bazel federation.

Fetch dependencies through the Bazel federation.

---

BUILD
WORKSPACE
cc/BUILD
cc/defs.bzl
cc/version.bzl
distro/BUILD
distro/README.md
internal_deps.bzl
internal_setup.bzl

This commit allows the creation of distributions, with 0.0.1 being the first version.
See distro/README.md for details on how to build a release.
This commit also uses a new version of the Bazel federation that contains rules_pkg 0.2.2 instead of 0.2.1.
There are still some problems with the WORKSPACE stanza that is being printed by the release notes generation script, though:
- It references a //cc:deps.bzl file, which doesn't exist. I have to modify the scripts in rules_pkg to support a flag like 'has_deps'.
- It doesn't support the Bazel federation yet, since it always tells users to download code from the rules_cc repository.
NOTE: This PR is not yet ready to be merged, since I'll address the aforementioned TODOs first.

Use rules_pkg for building releases

---

cc/private/toolchain/unix_cc_configure.bzl

A potential fix for https://github.com/bazelbuild/bazel/issues/9392

Skip gcc build configuration options mentioning gold in ld.gold detection

---

WORKSPACE
cc/private/toolchain/osx_cc_configure.bzl
cc/private/toolchain/unix_cc_configure.bzl
cc/repositories.bzl

This is the new entry point for registering C++ toolchains (replacing
implicit cc_configure()).
While at it, fix one misnamed function and port bazelbuild/bazel@2682688.

Add rules_cc_toolchains to repositories.bzl

---

examples/my_c_compile/my_c_compile.bzl

See https://github.com/bazelbuild/bazel/issues/9017 for details

Stop using the deprecated items parameter. 

---

cc/private/toolchain/cc_configure.bzl
cc/repositories.bzl

To make the build green again.
Adding `name` attribute to `cc_configure` properly requires synchronization with Bazel and passing the name through to places where we didn't expect before (e.g. hardcoded labels in non-templated BUILD files etc.). I leave that to another day.

Disable `unnamed-macro` for `cc-configure`.

---

cc/private/toolchain/windows_cc_configure.bzl

Bazel presumed a trailing space in `clang-cl -v` output that is
no longer present in the 11.0.0 release, resulting in an injected newline
This PR resolves such corrupted file paths for LLVM 11.0.0 and later.

Resolve the clang-cl 11.0.0 version detection

---

.bazelci/presubmit.yml
examples/test_cc_shared_library/BUILD
examples/test_cc_shared_library/diamond_inheritance/BUILD
examples/test_cc_shared_library/diamond_inheritance/main.cc

This is a test of the scenario described in bazelbuild/bazel#12981.  Fails as described with the release version, and passes with HEAD now.
cc @oquenchil

Test allowing diamond inheritance of shared lib

---

cc/private/toolchain/osx_cc_configure.bzl

This is required since https://github.com/bazelbuild/bazel/pull/13449
Should fix https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2047#9b7530e6-d708-4852-938d-321d0af6e90c

Add armeabi_cc_toolchain_config.bzl to macOS config

---

cc/BUILD
cc/private/rules_impl/BUILD
cc/private/toolchain/BUILD
tools/migration/BUILD

This adds support for generating documentation for `.bzl` files which load these via [stardoc](https://github.com/bazelbuild/stardoc).

Added `bzl_srcs` targets which only contain `.bzl` files

---

cc/private/rules_impl/cc_flags_supplier.bzl
cc/private/rules_impl/compiler_flag.bzl
examples/my_c_archive/my_c_archive.bzl
examples/my_c_compile/my_c_compile.bzl
examples/write_cc_toolchain_cpu/write_cc_toolchain_cpu.bzl

Hey wonderful Bazel folks,
I'd been following this example (linked from https://docs.bazel.build/versions/main/integrating-with-rules-cc.html). While doing, I happened to notice that the code was still calling the deprecated find_cpp_toolchain. This threw me for a quick loop on Bazel rolling, so I figured I'd toss up a quick PR to fix it. See discussion below about \@bazel_tools.
Deprecation comment here: https://github.com/bazelbuild/rules_cc/blob/main/cc/toolchain_utils.bzl
Thanks for all you do!
Chris
(ex-Googler)

Move examples from deprecated @rules_cc//cc:find_cpp_toolchain -> @bazel_tools//tools/cpp:toolchain_utils.bzl

---

WORKSPACE
cc/BUILD

- point to bazelbuild/platforms for @platforms
- Use a newer version of rules_go for our internal rules.
- Make a bzl file used in a test visible to the tests.
I believe this fixes a build breakage in bazel at head and 5.3.0  #140 
cc: @aranguyen

Update WORKSPACE to account for bazel_tool//platforms going away.

---

MODULE.bazel

The next release for rules_cc would be 0.0.3, and migrate to new toolchain registration API.

Fix MODULE.bazel file

---

WORKSPACE

0.34.0 does not have https://github.com/bazelbuild/rules_go/pull/3272
https://github.com/bazelbuild/continuous-integration/issues/1404

update to latest version of rules_go

---

MODULE.bazel

Required due to a new buildifier release.

Fix MODULE.bazel formatting

---

cc/compiler/BUILD
tests/compiler_settings/BUILD
tests/compiler_settings/main.cc

As of Bazel 6.0.0, all Bazel-provided toolchains report consistent compiler names that can be matched on with `select`. Having a central place for `config_setting`s that can be used for this purpose makes it so that rulesets don't have to define them themselves and moving the compiler flag out of `@bazel_tools` becomes easier as it is no longer referenced directly.
Fixes https://github.com/bazelbuild/bazel/issues/14914

Add well-known compiler `config_setting`s

---

cc/toolchains/args/sysroot.bzl

It's possible for there to be some arguments that are naturally associated with the sysroot flag, for example on macOS there are associated framework search paths that should be added with `-F{sysroot}/Library/Frameworks`. There are also warnings flags you might want to add such as `-Werror=missing-sysroot`. In this case I think it's nicer to provide them alongside the sysroot definition, instead of having to create a custom cc_args for them.

Allow extra args to cc_sysroot

---

cc/toolchains/actions/BUILD

The majority of the time objc_compile is identical to C/C++ compiles. Because of this I think by default all of those flags should apply here. This is a bit funny since the current builtin toolchain doesn't support Objective-C at all and that's only in the apple_support toolchain, but new toolchains using these rules may want to support this.
Without this things like `--objccopt` just don't work out of the box.

Add objc_compile to compile_actions

---

cc/private/BUILD

the glob pattern `**/*.bzl` doesn't match anything there, and this is bad for `--incompatible_disallow_empty_glob`. This PR removes the offending line.

Fix empty glob in cc/private/BUILD

---

cc/compiler/BUILD

I'm using emscripten for compiling some wasm and they use a different compiler identifier for their bazel toolchain. I think emscripten is different enough that it warrants it's own compiler setting dispite the recommendation that other toolchains use the already established identifiers.
Here's where it's being set in their toolchain: https://github.com/emscripten-core/emsdk/blob/93360d3670018769b424e4e8f1d3d9b26d32c977/bazel/emscripten_toolchain/toolchain.bzl#L68

add emscripten compiler config_setting

---

cc/private/toolchain/unix_cc_toolchain_config.bzl

It uses the same name as the feature itself.

Remove redundant with_feature_set for sanitizers

---

cc/toolchains/tool_map.bzl
docs/toolchain_api.md
examples/rule_based_toolchain/toolchain/tools/BUILD.bazel
tests/rule_based_toolchain/tool_map/BUILD
tests/rule_based_toolchain/tool_map/tool_map_test.bzl

Deduplicate tools for `cc_tool_map`

---

cc/private/toolchain/windows_cc_configure.bzl

This essentially reverts bazelbuild/bazel#23337 now that the toolchain configuration has been moved here. clang-cl does support assembly just like other clang variants and unlike MASM supports assembly using native AT&T syntax as with regular clang. MSVC-style assembly requires using MASM, which continues to be available in the MSVC toolchain.
This has previously been discussed in bazelbuild/bazel#24152 and reverted for Bazel 7.4.1 in bazelbuild/bazel#24211. Ideally, we'd want to have some mechanism to make assembler selection configurable and support several kinds of asm syntax in the future.
CC @meteorcloudy @michaelsiegrist

Use clang-cl assembler in clang-cl toolchain again

---

MODULE.bazel
WORKSPACE
cc/defs.bzl
cc/private/rules_impl/BUILD
cc/private/rules_impl/failing_cc_proto_library.bzl
cc/private/rules_impl/native.bzl

Cherrypick: 4b1c73e659a95a2eddd90236b636996af0042072
Copybara Import from https://github.com/bazelbuild/rules_cc/pull/449
BEGIN_PUBLIC
Remove dependency on protobuf (#449)
This is a new attempt, which is slightly softer than before. It only fails on Bazel8 and later, because it uses native cc_proto_library, so that it doesn't need to depend on the protobuf repository.
Closes #449
END_PUBLIC
COPYBARA_INTEGRATE_REVIEW=https://github.com/bazelbuild/rules_cc/pull/449 from comius:cc-proto-library-removal-2 655d09580e59802fca299b07f2031b5c960dae65 PiperOrigin-RevId: 791120562
Change-Id: I94e82caf10d08283d4730982b2959058bed4da2d

[0.1.x] Remove dependency on protobuf
